### ISSUE TITLE
error ****************

### ISSUE THREAD

**Issue by tk-t0n0y** [RedSiege/EyeWitness#562]
## OS 
win 10

after some successful  screenshot it show this

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr pUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at System.Windows.Forms.UnsafeNativeMethods.IHTMLDocument2.GetLocation()
   at System.Windows.Forms.WebBrowser.get_Document()
   at System.Windows.Forms.WebBrowser.get_ReadyState()
   at EyeWitness.WebsiteSnapshot._GenerateWebSiteImage()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mattgrandy** [comment]
This is likely due to how the threading is being executed. I ran into this while testing but it was rare and not repeatable (happened sporadically for different URLs). Will look into it when I have time but it may take a bit unfortunately.

**Comment by Relkci** [comment]
I doubt code has changed that would have addressed this.  That said, can you provide additional information, perhaps the URL that failed the screenshot?

**Comment by Relkci** [comment]
Closing until we have more information
