### ISSUE TITLE
Received exception on windows 11.

### ISSUE THREAD

**Issue by agrawalsmart7** [RedSiege/EyeWitness#600]
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr pUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at System.Windows.Forms.UnsafeNativeMethods.IHTMLDocument2.GetLocation()
   at System.Windows.Forms.WebBrowser.get_Document()
   at System.Windows.Forms.WebBrowser.get_ReadyState()
   at EyeWitness.WebsiteSnapshot._GenerateWebSiteImage() in C:\Users\{}\testing\EyeWitness\CS\EyeWitness\WebsiteSnapshot.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TheProdigyLeague** [comment]
hope this helps
`>>>from github.com/FortyNorthSecurity/EyeWitness/issues/600
@argrawalsmart7
PS>Get-Module FortyNorthSecurity
$ --git usr --clone
>>> import maths
>>> import __init__
>>> import OS
>>> from Handler -write remote ["ACCESS"] while exception -read -write
>>>3.14/*0
>>>import os
>>>if HKEY://C:/usr/pwd/desktop/sys32/code.exe throw, "ERROR, INVALID MEMORY :(0xC0000005/bin"
>>>import --mod
<xml>System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr pUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)</xml>
[!][ThreadStatic]::.c/static CopyCtorStubDesc s_copyCtorStubDesc; static internal {void} SetCopyCtorCookieChain(IntPtr pStubArg, IntPtr pUnmngThis, int dwStubFlags, IntPtr pCookie...
$ at System.Windows.Forms.UnsafeNativeMethods.IHTMLDocument2.GetLocation(NUL)
$ at System.Windows.Forms.WebBrowser.get_Document(NUL)
$ at System.Windows.Forms.WebBrowser.get_ReadyState(NUL)
$ at EyeWitness.WebsiteSnapshot._GenerateWebSiteImage(NUL); 
    in :root C:\Users{NUL}\testing\EyeWitness\CS\EyeWitness\WebsiteSnapshot.cs:line 94
$ at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
$ at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
$ at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
$ at System.Threading.ThreadHelper.ThreadStart(NUL)`

**Comment by Relkci** [comment]
Recent build today works (win 11 net 4.8)  Can you provide more information about the running environment?
![image](https://github.com/RedSiege/EyeWitness/assets/29710634/7650d7e0-9857-4712-a456-8b505dd75f46)

**Comment by Relkci** [comment]
no response/closing
